"use client";
import Head from "next/head";
import "./styles/globals.css";
import "./styles/theme.scss";
import type { Metadata } from "next";
import { Be_Vietnam_Pro, Inter } from "next/font/google";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [windowWidth, setWindowWidth] = useState(0);

  useEffect(() => {
    setWindowWidth(window.innerWidth);
    document.documentElement.style.setProperty(
      "--vw",
      `${window.outerWidth}px`
    );
  }, []);

  useEffect(() => {
    window.addEventListener("resize", () =>
      document.documentElement.style.setProperty(
        "--vw",
        `${window.outerWidth}px`
      )
    );

    return () => {
      window.removeEventListener("resize", () => setWindowWidth(0));
    };
  }, [windowWidth]);
  return (
    <html lang="en">
      <body className={""}>{children}</body>
    </html>
  );
}
